; Script generated by SaikoSoundboard Release Tooling
; Inno Setup Script for SaikoSoundboard Beta v0.4.0

#define MyAppName "SaikoSoundboard"
#define MyAppVersion "0.4.0-Beta"
#define MyAppPublisher "Saiko Interactive"
#define MyAppURL "https://github.com/your-username/SaikoSoundboard"
#define MyAppExeName "SaikoSoundboard.exe"
#define SourceDir "..\dist\SaikoSoundboard-v0.4.0-beta"

[Setup]
AppId={{D37B46F1-92A3-4F8A-B801-71EAA5D4309A}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
LicenseFile=..\README.md
InfoBeforeFile=permissions.txt
OutputDir=..\dist
OutputBaseFilename=SaikoSoundboard-0.4.0-Beta-Setup
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=lowest
UninstallDisplayIcon={app}\{#MyAppExeName}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#SourceDir}\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
function IsVirtualCableInstalled(): Boolean;
begin
  Result := RegKeyExists(HKLM, 'SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\VB-Cable_is1') or
            RegKeyExists(HKLM, 'SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\VB-Cable_is1') or
            RegKeyExists(HKLM, 'SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Virtual Audio Cable') or
            RegKeyExists(HKLM, 'SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Virtual Audio Cable');
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
  begin
    if not IsVirtualCableInstalled() then
    begin
      MsgBox('Notice: SaikoSoundboard multi-track application audio recording requires a Virtual Audio Cable driver (e.g. VB-Cable or Virtual Audio Cable) to route isolated app audio streams. None were detected on your system.' + #13#10#13#10 +
             'You can install a virtual cable driver separately to utilize the multi-track recording feature.', mbInformation, MB_OK);
    end;
  end;
end;
